name: "Add labels to pull requests"
on:
- pull_request_target
- push
- pull_request

jobs:
  labeler:
    name: Label Changes
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml
        
