name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request: 
    branches: 
      - "**"
  push: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.10'
      - name: Install Dependencies
        run: npm install
      - name: Generate Build
        run: npm ci
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v4
        with:
          name: recipes-build
          path: dist


